//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://fonlow.com/WorkflowDemo", ClrNamespace="Fonlow.WcfServic1.Client")]

namespace Fonlow.WcfServic1.Client
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://fonlow.com/WorkflowDemo")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fonlow.com/WorkflowDemo", ConfigurationName="Fonlow.WcfServic1.Client.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fonlow.com/WorkflowDemo/IService1/GetData", ReplyAction="http://fonlow.com/WorkflowDemo/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fonlow.com/WorkflowDemo/IService1/GetData", ReplyAction="http://fonlow.com/WorkflowDemo/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fonlow.com/WorkflowDemo/IService1/GetDataUsingDataContract", ReplyAction="http://fonlow.com/WorkflowDemo/IService1/GetDataUsingDataContractResponse")]
        Fonlow.WcfServic1.Client.CompositeType GetDataUsingDataContract(Fonlow.WcfServic1.Client.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fonlow.com/WorkflowDemo/IService1/GetDataUsingDataContract", ReplyAction="http://fonlow.com/WorkflowDemo/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Fonlow.WcfServic1.Client.CompositeType> GetDataUsingDataContractAsync(Fonlow.WcfServic1.Client.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fonlow.com/WorkflowDemo/IService1/RunWaitOrDelay", ReplyAction="http://fonlow.com/WorkflowDemo/IService1/RunWaitOrDelayResponse")]
        bool RunWaitOrDelay(int seconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fonlow.com/WorkflowDemo/IService1/RunWaitOrDelay", ReplyAction="http://fonlow.com/WorkflowDemo/IService1/RunWaitOrDelayResponse")]
        System.Threading.Tasks.Task<bool> RunWaitOrDelayAsync(int seconds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Fonlow.WcfServic1.Client.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Fonlow.WcfServic1.Client.IService1>, Fonlow.WcfServic1.Client.IService1
    {
        
        public Service1Client()
        {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public Fonlow.WcfServic1.Client.CompositeType GetDataUsingDataContract(Fonlow.WcfServic1.Client.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Fonlow.WcfServic1.Client.CompositeType> GetDataUsingDataContractAsync(Fonlow.WcfServic1.Client.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool RunWaitOrDelay(int seconds)
        {
            return base.Channel.RunWaitOrDelay(seconds);
        }
        
        public System.Threading.Tasks.Task<bool> RunWaitOrDelayAsync(int seconds)
        {
            return base.Channel.RunWaitOrDelayAsync(seconds);
        }
    }
}

